### ISSUE TITLE
README how-to steps need improvement

### ISSUE THREAD

**Issue by nvlgzr** [j2l/walk-and-graph-svelte-components#1]
First, I tried my best to, as you say, "npx this project":

```bash
$ npx j2l/walk-and-graph-svelte-components src/main.js
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/c/.npm/_cacache/tmp/git-clone-6167f725/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/c/.npm/_cacache/tmp/git-clone-6167f725/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/c/.npm/_logs/2022-03-15T05_01_16_226Z-debug.log
```

Then I copy-pasted your exact instructions:

```
$ git clone –depth 1 https://github.com/j2l/walk-and-graph-svelte-components.git
fatal: Too many arguments.

usage: git clone [<options>] [--] <repo> [<dir>]

    -v, --verbose         be more verbose
    -q, --quiet           be more quiet
<…snip!>
```

Turns out that's just a typo…probably some over-eager editor swapped out `--depth` for `—depth` somewhere along the way. Easy to miss. Trying again…

```
$ git clone --depth 1 https://github.com/j2l/walk-and-graph-svelte-components.git
Cloning into 'walk-and-graph-svelte-components'...
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 16 (delta 0), reused 12 (delta 0), pack-reused 0
Receiving objects: 100% (16/16), 37.02 KiB | 1.42 MiB/s, done.
```

Better. But still, can't get it to work…

```
$ node walk-and-graph-svelte-components/walk.js src/main.js 
(node:87771) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/c/Documents/2-Ongoing/navelgazer/fngrng/walk-and-graph-svelte-components/walk.js:8
import fs from 'fs';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47
```

It might be helpful to create a dummy project — something outside of this one — and try to follow your own README steps as if you don't know how the project works.

Looks promising, though! I'm interested to give it a shot once the instructions can be followed in a more-or-less brainless manner. 😉

**Comment by j2l** [comment]
Thanks for the feedback @nvlgzr 
I fixed your points:
- `npx degit` (would you please test it)
- `--depth` typo
- added a package.json using `npm init -y` and adding `"type": "module"` to it (testd on my side, please test to confirm it's working for you)
Since this tool is made to graph an existing `src/` in a svelte project, I removed `package.json` but you're right it should work as is.
I made this project mainly because I couldn't get depcruise to work and it's now fixed, see https://github.com/sverweij/dependency-cruiser/issues/563
Feel free to close or comment it.

**Comment by nvlgzr** [comment]
Hey there! Sorry for the delayed response.

I got your demo project to work, then tried it with a [project of my own](https://github.com/nvlgzr/fngrng). Unfortunately, I kept getting "no such file or directory" errors.

The first few were due to my leaving out ".js" from certain imports…

```
import { foo } from "iAmAJavascriptFile"
```

vs.

```
import { foo } from "iAmAJavascriptFile.js"
```

That's easy enough to work around, but then I got the same errors with my "svelte" imports so that, for instance, this line in _volatileStore.js_…

```
import { derived, readable, writable } from "svelte/store";
```

…seems to be triggering a similar error:

```
file: src/./volatileStore.js
[ 'svelte/store' ]
file:///Users/c/Documents/2-Ongoing/navelgazer/fngrng/walk.js:23
        if (err) throw err;
                 ^

[Error: ENOENT: no such file or directory, open 'src/svelte'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'src/svelte'
}
```

All that said, the README is vastly improved inasmuch as I can at least I can get the demo running. I'll go ahead and close this issue.

Feel free to ping me if you would like further feedback. Otherwise, _je vous laisse tranquille_.

# 🦦
